In [1]:
import pandas as pd
import numpy as np
import math
import os

# import for time, and file change
import json
from PIL import Image

# frequent updating
import time
import random

In [2]:
# define filepaths
workspace = "/Users/advaysingh/Documents/projects/hindi_classification/" 
#print("Current workspace:", workspace)

data = os.path.join(workspace, 'data/Hindi/')
dict_lib = os.path.join(workspace, 'data/dict.csv')
img_path = os.path.join(workspace, 'server/snapshot.png')
out_file = os.path.join(workspace, 'server/outputs.json')


In [3]:
# create train/test dicts with files and labels

def create_dict(x: str) -> dict:
    x_dict = {}
    i = 0
    for dir in os.listdir(os.path.join(data, x)):
        for file in os.listdir(os.path.join(data, x, dir)):
            x_dict[os.path.join(data, x, dir, file)] = i
        i += 1
    return x_dict

# make pandas df

train_df = pd.DataFrame.from_dict(create_dict('Train'), orient='index')
test_df = pd.DataFrame.from_dict(create_dict('Test'), orient='index')

train_df.head()

0
/Users/advaysingh/Documents/projects/hindi_clas...  0
/Users/advaysingh/Documents/projects/hindi_clas...  0
/Users/advaysingh/Documents/projects/hindi_clas...  0
/Users/advaysingh/Documents/projects/hindi_clas...  0
/Users/advaysingh/Documents/projects/hindi_clas...  0

In [4]:
# Activations class
class Activation:
    # can add more types
    def __init__(self, act_type: str) -> None:
        self.act = act_type

    def print_act(self) -> None:
        return self.act
    
    def compute(self, z: float) -> float:

        # Sigmoid function
        if (self.act == 'sigmoid'):
            return 1 / (1 + math.exp(z))
        
        # ReLU function
        elif (self.act == 'relu'):
            if (z < 0): return 0
            return z

    def prime(self, z: float) -> float:

        # Sigmoid prime
        if (self.act == 'sigmoid'):
            return (self.compute(z))(1 - self.compute(z))
        
        # ReLU prime
        if (self.act == 'relu'):
            if (z < 0): return 0
            return 1


def softmax(i: int, costs: list) -> float:
    return costs[i] / sum(costs)

def softmax_prime(i: int, costs: list) -> float:
    softmax(i, costs)(1 - softmax(i, costs))


    
a = Activation('sigmoid')

print(a.compute(233.2))

5.278698047466735e-102


In [9]:
class Model:
    def __init__(self, train_df: pd.DataFrame,
                  act: Activation, layers: list, step: float, stochastic: bool) -> None:
        self.train_df = train_df

        # create activation function
        self.act = act
        self.layers = layers

        # init weight and bias with # layers np arrays
        self.all_weights = [None] * (int(len(layers)))
        self.all_bias = [None] * (int(len(layers)))
        for i in range(len(layers)):
            self.all_weights[i] = self.random_arrs(i)
            self.all_bias[i] = self.random_arrs(i)

        # init learn speed
        self.speed = step

        # determine gradient decent type
        self.stochastic = stochastic

    def random_arrs(self, layer: int):
        if (layer == 0):
            return(np.random.rand(self.layers[layer], int(len(train_df))))
        else:
            return(np.random.rand(self.layers[layer], self.layers[layer - 1]))

    def img_to_np(self, dir) -> np.array:
        return np.array(Image.open(dir)).flatten()
    
    def print_img(self) -> None:
        for img_dir, row in self.train_df.iterrows():
            print(self.img_to_np(img_dir), row[0])

    def print_weights(self) -> None:
        for arr in self.all_weights:
            print(arr.shape)

    def prop_forward(self, inputs: list, layer: int) -> list:
        a_vals = [None] * int(self.layers[layer])
        for a in range(len(a_vals)):
            for x in range(len(inputs)):
                if (layer == int(len(self.layers))):
                    #TODO: determine .product formula
                    a_vals[a] = softmax(self.all_weights[layer][a, x] * inputs[x]+ self.all_bias[layer][a, x])
                a_vals[a] = self.act.compute(self.all_weights[layer][a, x] * inputs[x]+ self.all_bias[layer][a, x])
        return a_vals
    
    
    def prop_backward(self, x: list, y: list, e: list, layer: int) -> None:
        # if final layer
        if (layer == len(self.layers)):
            # iter through weights (using index so can be done for biases)
            for i in range(len(y)):
                for j in range(len(x)):
                    self.all_weights[layer][i][j] += e[i] * y[i] * (1 - y[i]) * x[j]
                    self.all_bias[layer][i][j] += e[i] * y[i] * (1 - y[i])
        # recurse to the following layer
        #else:
            #self.all_weights[layer][]

        # prop_forward for all of the layers
        print("in progress")
        # change weights appropriatly

    def train(self, epochs: int) -> None:
        # call back prop with dataset epochs times
        print("training in progress")

    def classify(self, img: np.array) -> int:
        print("classification in progress")

    def test(self, test_df: pd.DataFrame) -> None:
        for img_dir, row in test_df.iterrows():
            print(self.img_to_np(img_dir), row[0])

    def save(self) -> None:
        print("in_progress") # save into csv file. Later use this file to prop forwars predicting the outcome



In [10]:

cnn = Model(train_df.head(), Activation('sigmoid'), [10, 10, 10, 46], 1.2, False)
#cnn.print_img()
#cnn.print_weights()
some_vals = cnn.prop_forward([1, 2, 3, 45, 5], 3)
cnn.prop_backward([1, 2, 3, 45, 5], some_vals, [-.5] * 5, 3)
print (some_vals)
#cnn.test(test_df)

in progress
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 ... 0 0 0] 0
[0 0 0 .

In [109]:
import json
import time
import random

from PIL import Image


def update_json_file(hindi_value, english_value):
    with open(out_file, 'r') as file:
        data = json.load(file)
    data['hindi'] = hindi_value
    data['english'] = english_value
    with open(out_file, 'w') as file:
        json.dump(data, file, indent=4)

# Define a list of possible values if applicable
hindi_values = ["हिं", "नया", "मूल्य", "उदाहरण"]
english_values = ["Eng", "New", "Value", "Example"]

# Loop to update the JSON file every second with a random value
try:
    while True:
        # Generate a random value from the lists
        new_hindi_value = random.choice(hindi_values)
        new_english_value = random.choice(english_values)

        update_json_file(new_hindi_value, new_english_value)
        
        # Print the new values (for debug purposes)
        # print(f'Updated JSON file with hindi: {new_hindi_value}, english: {new_english_value}')

        # read in and resize img
        img = Image.open(img_path).convert("L").resize((32, 32))
 
        # read in image for debugging
        """img.show("img to classify")
        print(img.format)
        print(img.mode)
        print(img.size)"""

        # create np array and resize
        img_data = np.array(img).flatten()
        print(img_data.shape)
        print(img_data)

        
        time.sleep(10)  # Wait for 1 second
except KeyboardInterrupt:
    print("Update stopped by user.")

(1024,)
[0 0 0 ... 0 0 0]
Update stopped by user.
